import data from "../data/cards.json";
import { activePlayer, chooseBestNpcHeir, chooseNpcAttack, heirChoices, legalAttackers, legalTargets, replenishFromDiscard, replenishFromUnused, resolveAmateurAttack, resolveNpcReplenishment, skipReplenishment, type AmateurAttack, type AmateurCard, type AmateurEvent, type AmateurState, type PreparedAmateurGame, type PreparedPlayer } from "./amateur";
import { createRandomState, randomSource } from "./random";
import type { MultiplayerRoomSettings, MultiplayerSeat } from "./multiplayer";
import type { Stat } from "./types";

const canonical = data.cards as Array<{id:string;name:string;factionId:string;type:AmateurCard["type"];strength:number;zeal:number;wealth:number;deckCopies:number;availableInPrototype:boolean}>;
const shuffle=<T,>(a:T[],r:()=>number)=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function deal(factionId:string,r:()=>number){const cards=canonical.filter(c=>c.factionId===factionId&&c.availableInPrototype).flatMap(c=>Array.from({length:c.deckCopies},():AmateurCard=>({id:crypto.randomUUID(),definitionId:c.id,name:c.name,factionId:c.factionId,type:c.type,strength:c.strength,zeal:c.zeal,wealth:c.wealth,face:"down"})));const leaders=shuffle(cards.filter(c=>c.type==="leader"),r);const non=shuffle(cards.filter(c=>c.type!=="leader"),r);return{army:non.slice(0,10),unused:shuffle([...non.slice(10),...leaders],r)}}

export function prepareMultiplayerAmateur(seats:MultiplayerSeat[],settings:MultiplayerRoomSettings):PreparedAmateurGame{const random=createRandomState();const r=randomSource(random);const players:PreparedPlayer[]=seats.sort((a,b)=>a.seatOrder-b.seatOrder).map(s=>({id:s.userId??s.id,factionId:s.factionId!,controller:s.controller,...deal(s.factionId!,r),discard:[],eliminated:false}));const human=players.flatMap((p,i)=>p.controller==="human"?[i]:[]),npc=players.flatMap((p,i)=>p.controller==="npc"?[i]:[]);const candidates=settings.openingPlayer==="human"?human:settings.openingPlayer==="npc"&&npc.length?npc:players.map((_,i)=>i);return{players,activePlayerIndex:candidates[Math.floor(r()*candidates.length)],nileFloods:settings.nileFloods,victoryMode:settings.victoryMode??"standard",random}}
export function startMultiplayerAmateur(prepared:PreparedAmateurGame,selections:Record<string,string>):AmateurState{const players=prepared.players.map(p=>{const heir=p.controller==="npc"?chooseBestNpcHeir(p):p.unused.find(c=>c.id===selections[p.id]&&c.type==="leader");if(!heir)throw new Error("Every human must choose a valid heir.");return{...p,heir:{...heir,face:"up" as const},unused:p.unused.filter(c=>c.id!==heir.id)}});return{version:1,mode:"amateur",players,activePlayerIndex:prepared.activePlayerIndex,phase:"attack",nileFloods:prepared.nileFloods,victoryMode:prepared.victoryMode,round:1,random:prepared.random}}
export const amateurHeirChoices=(p:PreparedAmateurGame,id:string)=>heirChoices(p,id);
export type AmateurMultiplayerReview={kind:"result";attack:AmateurAttack;events:AmateurEvent[];attacker:AmateurCard;target:AmateurCard;scores:Array<{playerId:string;cardId:string;base:number;die:number;total:number}>;tie:boolean;winnerId?:string};
export function resolveMultiplayerAmateur(state:AmateurState,attack:AmateurAttack):AmateurMultiplayerReview{const a=state.players.find(p=>p.id===activePlayer(state).id)!;const d=state.players.find(p=>p.id===attack.targetPlayerId)!;const attacker=structuredClone(a.heir.id===attack.attackerId?a.heir:a.army.find(c=>c.id===attack.attackerId)!);const target=structuredClone(d.heir.id===attack.targetId?d.heir:d.army.find(c=>c.id===attack.targetId)!);const events=resolveAmateurAttack(state,attack);const scores=events.filter((e):e is Extract<AmateurEvent,{type:"score"}>=>e.type==="score").map(({playerId,cardId,base,die,total})=>({playerId,cardId,base,die,total}));const tie=events.some(e=>e.type==="tie");const high=Math.max(...scores.map(s=>s.total));return{kind:"result",attack,events,attacker,target,scores,tie,winnerId:tie?undefined:scores.find(s=>s.total===high)?.playerId}}
export function publicAmateurState(state:AmateurState){const card=(c:AmateurCard,force=false)=>force||c.face==="up"?c:{id:c.id,face:c.face};return{...state,random:{seed:state.random.seed},players:state.players.map(p=>({...p,army:p.army.map(c=>card(c)),heir:card(p.heir,true),unused:Array.from({length:p.unused.length},(_,i)=>({id:`unused-${i}`,face:"down"})),discard:p.discard.map(c=>card(c,true))}))}}
export {activePlayer,chooseNpcAttack,legalAttackers,legalTargets,replenishFromDiscard,replenishFromUnused,resolveNpcReplenishment,skipReplenishment};
export type {AmateurAttack,AmateurState,Stat};
