import type{BeginnerState,Card,GameEvent,Player,Stat,TieState}from"./types";
export type RandomSource=()=>number;
export function surviving(p:Player){return p.cards.filter(c=>!c.discarded)}
export function nextCard(p:Player,excluded=new Set<string>()):Card|undefined{if(!surviving(p).length)return;for(let n=0;n<p.cards.length;n++){const i=(p.cursor+n)%p.cards.length;const c=p.cards[i];if(!c.discarded&&!excluded.has(c.id)){p.cursor=(i+1)%p.cards.length;return c}}}
export function score(card:Card,stat:Stat,die=0){return card[stat]+die}
export function eliminateEmptyPlayers(state:BeginnerState){for(const p of state.players)p.eliminated=surviving(p).length===0;const active=state.players.filter(p=>!p.eliminated);if(active.length===1){state.phase="complete";state.winnerId=active[0].id}}
export function advanceSelector(state:BeginnerState){for(let n=1;n<=state.players.length;n++){const i=(state.selectorIndex+n)%state.players.length;if(!state.players[i].eliminated){state.selectorIndex=i;return}}}
const die=(rng:RandomSource)=>Math.floor(rng()*6)+1;
function getPlayer(state:BeginnerState,id:string){const p=state.players.find(x=>x.id===id);if(!p)throw new Error(`Unknown player ${id}`);return p}
function discard(state:BeginnerState,ids:string[],events:GameEvent[]){for(const id of ids){const p=getPlayer(state,id);const cardIds=state.tie?.usedCardIds[id]??[];for(const cardId of cardIds){const c=p.cards.find(x=>x.id===cardId);if(c)c.discarded=true}if(cardIds.length)events.push({type:"cards-discarded",playerId:id,cardIds:[...cardIds]})}}
function eliminate(state:BeginnerState,events:GameEvent[]){for(const p of state.players){if(!p.eliminated&&!surviving(p).length){p.eliminated=true;events.push({type:"player-eliminated",playerId:p.id})}}const active=state.players.filter(p=>!p.eliminated);if(active.length===1){state.phase="complete";state.winnerId=active[0].id;events.push({type:"game-won",playerId:active[0].id});return true}return false}
function finish(state:BeginnerState,winnerId:string,events:GameEvent[]){const participants=state.tie?.participantIds??[];discard(state,participants.filter(id=>id!==winnerId),events);events.push({type:"comparison-won",playerId:winnerId});state.tie=undefined;state.selectedStat=undefined;if(eliminate(state,events))return;advanceSelector(state);state.round++;state.phase="select";events.push({type:"selector-advanced",playerId:state.players[state.selectorIndex].id})}
function exhaustedTie(state:BeginnerState,events:GameEvent[],rng:RandomSource){let contenders=[...(state.tie?.participantIds??[])];for(let guard=0;guard<100&&contenders.length>1;guard++){const rolls=contenders.map(id=>({id,value:die(rng)}));for(const r of rolls)events.push({type:"die-rolled",playerId:r.id,value:r.value,reason:"exhausted-tie"});const high=Math.max(...rolls.map(r=>r.value));contenders=rolls.filter(r=>r.value===high).map(r=>r.id)}if(contenders.length!==1)throw new Error("Unable to resolve exhausted tie");finish(state,contenders[0],events)}
const hasAvailable=(p:Player,excluded:Set<string>)=>p.cards.some(c=>!c.discarded&&!excluded.has(c.id));
export function playComparison(state:BeginnerState,stat:Stat,rng:RandomSource=Math.random):GameEvent[]{if(state.phase!=="select"&&state.phase!=="tie")throw new Error("Comparison cannot be played now");const events:GameEvent[]=[];const selector=state.players[state.selectorIndex];events.push({type:"stat-selected",playerId:selector.id,stat});state.selectedStat=stat;if(!state.tie){const ids=state.players.filter(p=>!p.eliminated).map(p=>p.id);state.tie={participantIds:ids,usedCardIds:Object.fromEntries(ids.map(id=>[id,[]]))}as TieState}let entries=state.tie.participantIds.map(id=>{const p=getPlayer(state,id);const used=new Set(state.tie!.usedCardIds[id]);return{id,p,card:nextCard(p,used)}});if(entries.every(x=>!x.card)){exhaustedTie(state,events,rng);return events}const exhausted=entries.filter(x=>!x.card).map(x=>x.id);if(exhausted.length){discard(state,exhausted,events);entries=entries.filter(x=>Boolean(x.card));state.tie.participantIds=entries.map(x=>x.id);if(entries.length===1){finish(state,entries[0].id,events);return events}}const results=entries.map(({id,card})=>{const c=card!;const wasFaceDown=c.face==="down";c.face="up";state.tie!.usedCardIds[id].push(c.id);events.push({type:"card-revealed",playerId:id,cardId:c.id,wasFaceDown});const roll=state.nileFloods?die(rng):0;if(roll)events.push({type:"die-rolled",playerId:id,value:roll,reason:"nile-floods"});const total=score(c,stat,roll);events.push({type:"score",playerId:id,cardId:c.id,base:c[stat],die:roll,total});return{id,total}});const high=Math.max(...results.map(r=>r.total));const leaders=results.filter(r=>r.total===high).map(r=>r.id);const lower=state.tie.participantIds.filter(id=>!leaders.includes(id));discard(state,lower,events);state.tie.participantIds=leaders;if(leaders.length===1){finish(state,leaders[0],events);return events}state.phase="tie";events.push({type:"tie",playerIds:[...leaders]});if(leaders.every(id=>!hasAvailable(getPlayer(state,id),new Set(state.tie!.usedCardIds[id]))))exhaustedTie(state,events,rng);return events}
