import{describe,expect,it}from"vitest";import{playComparison}from"./beginner";import type{BeginnerState,Card,Player}from"./types";
const c=(id:string,s:number,z:number,w:number):Card=>({id,name:id,factionId:"f",strength:s,zeal:z,wealth:w,face:"down",discarded:false});
const p=(id:string,cards:Card[]):Player=>({id,factionId:id,controller:"npc",cards,cursor:0,eliminated:false});
const state=(players:Player[],nileFloods=false):BeginnerState=>({version:1,players,selectorIndex:0,phase:"select",nileFloods,round:1});
describe("Beginner comparison state machine",()=>{
it("retains the winner, discards losers, and advances selection clockwise",()=>{const s=state([p("a",[c("a1",5,1,1),c("a2",1,1,1)]),p("b",[c("b1",2,1,1),c("b2",1,1,1)])]);const e=playComparison(s,"strength");expect(s.players[0].cards[0].discarded).toBe(false);expect(s.players[1].cards[0].discarded).toBe(true);expect(s.selectorIndex).toBe(1);expect(s.phase).toBe("select");expect(e.some(x=>x.type==="comparison-won"&&x.playerId==="a")).toBe(true)});
it("keeps every tying and winning card for the eventual winner",()=>{const s=state([p("a",[c("a1",2,2,2),c("a2",8,1,1)]),p("b",[c("b1",2,2,2),c("b2",3,1,1)])]);playComparison(s,"wealth");expect(s.phase).toBe("tie");playComparison(s,"strength");expect(s.players[0].cards.every(x=>!x.discarded)).toBe(true);expect(s.players[1].cards.every(x=>x.discarded)).toBe(true);expect(s.winnerId).toBe("a")});
it("allows the original selector to control a tie after leaving it",()=>{const s=state([p("a",[c("a1",1,1,1)]),p("b",[c("b1",5,1,1),c("b2",7,1,1)]),p("c",[c("c1",5,1,1),c("c2",2,1,1)])]);playComparison(s,"strength");expect(s.selectorIndex).toBe(0);expect(s.tie?.participantIds).toEqual(["b","c"]);const e=playComparison(s,"strength");expect(e[0]).toEqual({type:"stat-selected",playerId:"a",stat:"strength"});expect(s.winnerId).toBe("b")});
it("uses repeated d6 rolls when tied players exhaust the sequence",()=>{const rolls=[0,.9,.2,.2,0,.8];let i=0;const s=state([p("a",[c("a1",2,2,2)]),p("b",[c("b1",2,2,2)])]);const e=playComparison(s,"zeal",()=>rolls[i++]);expect(s.winnerId).toBe("b");expect(e.filter(x=>x.type==="die-rolled"&&x.reason==="exhausted-tie").length).toBe(2)});
it("adds one Nile Floods die to each competing card",()=>{const rolls=[0,.99];let i=0;const s=state([p("a",[c("a1",5,1,1),c("a2",1,1,1)]),p("b",[c("b1",1,1,1),c("b2",1,1,1)])],true);const e=playComparison(s,"strength",()=>rolls[i++]);const scores=e.filter(x=>x.type==="score");expect(scores.map(x=>x.type==="score"?x.die:0)).toEqual([1,6]);expect(s.players[0].cards[0].discarded).toBe(true)});
});
