import data from "../data/cards.json";
import {activeMasterPlayer,autoArrangeMasterCards,chooseMasterNpcAttack,legalMasterAttackers,legalMasterTargets,masterArmySize,replenishMasterArmy,resolveMasterAttack,resolveMasterNpcReplenishment,skipMasterReplenishment,validateInitialArmy,type MasterAttack,type MasterCard,type MasterConstruction,type MasterEvent,type MasterPile,type MasterPlayer,type MasterState} from "./master";
import {createRandomState,randomSource} from "./random";
import type{MultiplayerRoomSettings,MultiplayerSeat}from"./multiplayer";
import type{Stat}from"./types";

const canonical=data.cards as Array<{id:string;name:string;factionId:string;type:MasterCard["type"];strength:number;zeal:number;wealth:number;deckCopies:number;availableInPrototype:boolean}>;
const shuffle=<T,>(a:T[],r:()=>number)=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const value=(c:MasterCard)=>c.strength+c.zeal+c.wealth;
function deck(factionId:string){return canonical.filter(c=>c.factionId===factionId&&c.availableInPrototype).flatMap(c=>Array.from({length:c.deckCopies},(_,i):MasterCard=>({id:crypto.randomUUID(),definitionId:c.id,name:c.name,factionId:c.factionId,type:c.type,strength:c.strength,zeal:c.zeal,wealth:c.wealth,face:"down"})))}
export type PreparedMasterMultiplayer={players:Array<{id:string;factionId:string;controller:"human"|"npc";leaders:MasterCard[];deck:MasterCard[]}>;activePlayerIndex:number;nileFloods:boolean;victoryMode:"standard"|"long";random:ReturnType<typeof createRandomState>};
export function prepareMultiplayerMaster(seats:MultiplayerSeat[],settings:MultiplayerRoomSettings):PreparedMasterMultiplayer{const random=createRandomState(),r=randomSource(random);const players=[...seats].sort((a,b)=>a.seatOrder-b.seatOrder).map(s=>{const cards=deck(s.factionId!),leaders=cards.filter(c=>c.type==="leader");return{id:s.userId??s.id,factionId:s.factionId!,controller:s.controller,leaders,deck:cards.filter(c=>c.type!=="leader")}});const human=players.flatMap((p,i)=>p.controller==="human"?[i]:[]),npc=players.flatMap((p,i)=>p.controller==="npc"?[i]:[]),choices=settings.openingPlayer==="human"?human:settings.openingPlayer==="npc"&&npc.length?npc:players.map((_,i)=>i);return{players,activePlayerIndex:choices[Math.floor(r()*choices.length)],nileFloods:settings.nileFloods,victoryMode:settings.victoryMode??"standard",random}}
export const masterMultiplayerHeirs=(p:PreparedMasterMultiplayer,id:string)=>p.players.find(x=>x.id===id)?.leaders??[];
function dealTwenty(cards:MasterCard[],r:()=>number){for(let n=0;n<1000;n++){const all=shuffle([...cards],r),army=all.slice(0,20),things=army.filter(c=>c.type==="thing").length,holders=army.filter(c=>c.type==="person"||c.type==="leader").length;if(army.length===20&&things<=holders)return{army,unused:all.slice(20)}}throw Error("Unable to deal a legal Master army")}
export type MasterDraft={construction:MasterConstruction;cards:Record<string,MasterCard[]>;piles:Record<string,MasterPile[]>;confirmed:string[]};
export function beginMultiplayerConstruction(p:PreparedMasterMultiplayer,selections:Record<string,string>):MasterDraft{const r=randomSource(p.random),cards:Record<string,MasterCard[]>={},piles:Record<string,MasterPile[]>={},players:MasterPlayer[]=p.players.map(x=>{const heir=x.controller==="npc"?[...x.leaders].sort((a,b)=>value(b)-value(a))[0]:x.leaders.find(c=>c.id===selections[x.id]);if(!heir)throw Error("Every human must choose an heir");const dealt=dealTwenty([...x.deck,...x.leaders.filter(c=>c.id!==heir.id)],r),setup=dealt.army.map(c=>({...c,face:x.controller==="human"?"up" as const:"down" as const}));if(x.controller==="human"){cards[x.id]=setup;piles[x.id]=[]}const army=x.controller==="npc"?autoArrangeMasterCards(setup,`${x.id}-pile`):[];return{id:x.id,factionId:x.factionId,controller:x.controller,army,heir:{...heir,face:"up"},unused:dealt.unused,discard:[],eliminated:false}});return{construction:{players,activePlayerIndex:p.activePlayerIndex,nileFloods:p.nileFloods,victoryMode:p.victoryMode,random:p.random},cards,piles,confirmed:[]}}
export function setDraftPiles(d:MasterDraft,id:string,piles:MasterPile[]){const cards=d.cards[id];if(!cards)throw Error("Unknown construction player");const ids=piles.flatMap(p=>p.cards.map(c=>c.id));if(new Set(ids).size!==ids.length||ids.some(x=>!cards.some(c=>c.id===x)))throw Error("Invalid construction draft");d.piles[id]=piles}
export function autoArrangeDraft(d:MasterDraft,id:string){d.piles[id]=autoArrangeMasterCards(d.cards[id],`${id}-pile`)}
export function confirmDraft(d:MasterDraft,id:string){if(!validateInitialArmy(d.piles[id],d.cards[id].map(c=>c.id)))throw Error("Every card must be assigned to a legal pile");if(!d.confirmed.includes(id))d.confirmed.push(id)}
export function startMultiplayerMaster(d:MasterDraft):MasterState{for(const p of d.construction.players)if(p.controller==="human"){if(!d.confirmed.includes(p.id))throw Error("Every human must confirm");p.army=d.piles[p.id].map(x=>({...x,cards:x.cards.map(c=>({...c,face:"down"}))}))}return{version:1,mode:"master",players:d.construction.players,activePlayerIndex:d.construction.activePlayerIndex,phase:"attack",nileFloods:d.construction.nileFloods,victoryMode:d.construction.victoryMode,round:1,random:d.construction.random}}
const publicCard=(c:MasterCard,show=false)=>show||c.face==="up"?c:{id:c.id,face:c.face};
export function publicMasterState(s:MasterState){return{...s,random:{seed:s.random.seed},players:s.players.map(p=>({...p,army:p.army.map(x=>({...x,cards:x.cards.map(c=>publicCard(c))})),heir:publicCard(p.heir,true),unused:Array.from({length:p.unused.length},(_,i)=>({id:`unused-${i}`,face:"down"})),discard:p.discard.map(c=>publicCard(c,true))}))}}
export type MasterMultiplayerReview={kind:"result";attack:MasterAttack;events:MasterEvent[];attacker:MasterCard[];target:MasterCard[];scores:Array<{playerId:string;unitId:string;base:number;die:number;total:number}>;tie:boolean;winnerId?:string};
function unit(p:MasterPlayer,id:string){return p.heir.id===id?[p.heir]:p.army.find(x=>x.id===id)!.cards}
export function resolveMultiplayerMaster(s:MasterState,a:MasterAttack):MasterMultiplayerReview{const ap=activeMasterPlayer(s),tp=s.players.find(p=>p.id===a.targetPlayerId)!,attacker=structuredClone(unit(ap,a.attackerUnitId)),target=structuredClone(unit(tp,a.targetUnitId)),events=resolveMasterAttack(s,a),scores=events.filter((e):e is Extract<MasterEvent,{type:"score"}>=>e.type==="score").map(({playerId,unitId,base,die,total})=>({playerId,unitId,base,die,total})),tie=events.some(e=>e.type==="tie"),high=Math.max(...scores.map(x=>x.total));return{kind:"result",attack:a,events,attacker,target,scores,tie,winnerId:tie?undefined:scores.find(x=>x.total===high)?.playerId}}
export{activeMasterPlayer,chooseMasterNpcAttack,legalMasterAttackers,legalMasterTargets,masterArmySize,replenishMasterArmy,resolveMasterNpcReplenishment,skipMasterReplenishment};
export type{MasterAttack,MasterCard,MasterPile,MasterState,Stat};
