import { adminSupabase, multiplayerConfigured, requestUser } from "@/lib/supabase-server";
import { amateurHeirChoices, activePlayer, chooseNpcAttack, legalAttackers, legalTargets, prepareMultiplayerAmateur, publicAmateurState, replenishFromDiscard, replenishFromUnused, resolveMultiplayerAmateur, resolveNpcReplenishment, skipReplenishment, startMultiplayerAmateur, type AmateurAttack, type AmateurState } from "@/game/amateur-multiplayer";
import { MULTIPLAYER_FACTIONS, type MultiplayerRoomSettings, type MultiplayerSeat } from "@/game/multiplayer";

type PlayerRow={id:string;user_id:string|null;display_name:string;controller:"human"|"npc";faction_id:string|null;seat_order:number};
type SetupState={stage:"heirs";prepared:any;selections:Record<string,string>};
type RoomRow={code:string;host_user_id:string;level:string;status:"waiting"|"active"|"complete"|"abandoned";settings:MultiplayerRoomSettings;game_state?:SetupState|AmateurState;review?:any;review_acks:string[];revision:number};
async function load(code:string){const s=adminSupabase();const[{data:r},{data:p}]=await Promise.all([s.from("nk_multiplayer_rooms").select("*").eq("code",code).maybeSingle(),s.from("nk_multiplayer_players").select("*").eq("room_code",code).order("seat_order")]);return{s,room:r as RoomRow|null,players:(p??[])as PlayerRow[]}}
function isSetup(v:any):v is SetupState{return v?.stage==="heirs"}
function payload(room:RoomRow,players:PlayerRow[],uid:string){const setup=isSetup(room.game_state)?room.game_state:undefined;const state=room.game_state&&!setup?room.game_state as AmateurState:undefined;return{code:room.code,status:room.status,isHost:room.host_user_id===uid,settings:room.settings,revision:room.revision,acknowledged:room.review_acks?.includes(uid)??false,seats:players.map(p=>({id:p.id,userId:p.user_id??undefined,displayName:p.display_name,controller:p.controller,factionId:p.faction_id??undefined,seatOrder:p.seat_order,isYou:p.user_id===uid})),stage:setup?"heirs":state?"game":"lobby",heirs:setup?amateurHeirChoices(setup.prepared,uid):undefined,heirsReady:setup?Object.keys(setup.selections).length:undefined,humanCount:players.filter(p=>p.controller==="human").length,state:state?publicAmateurState(state):undefined,review:room.review}}
async function auth(req:Request,raw:string){if(!multiplayerConfigured())return{error:Response.json({error:"Multiplayer has not been configured yet."},{status:503})};const user=await requestUser(req);if(!user)return{error:Response.json({error:"Your guest session could not be verified."},{status:401})};const x=await load(raw.toUpperCase());if(!x.room)return{error:Response.json({error:"That game no longer exists."},{status:404})};if(x.room.level!=="amateur")return{error:Response.json({error:"Open this room from its correct game level."},{status:409})};if(!x.players.some(p=>p.user_id===user.id))return{error:Response.json({error:"You are not a participant in this game."},{status:403})};return{...x,room:x.room,user}}
async function save(s:any,room:RoomRow,changes:any){const{data,error}=await s.from("nk_multiplayer_rooms").update({...changes,revision:room.revision+1,updated_at:new Date().toISOString()}).eq("code",room.code).eq("revision",room.revision).select().maybeSingle();return!error&&data}
export async function GET(req:Request,{params}:{params:Promise<{code:string}>}){const{code}=await params;const x=await auth(req,code);if("error"in x)return x.error;return Response.json(payload(x.room,x.players,x.user.id))}
export async function PATCH(req:Request,{params}:{params:Promise<{code:string}>}){const{code}=await params;const x=await auth(req,code);if("error"in x)return x.error;const{room,players,s,user}=x;const b=await req.json().catch(()=>({}));
 if(b.action==="rematch"){if(room.host_user_id!==user.id)return Response.json({error:"Only the host can start a rematch."},{status:403});if(room.status!=="complete")return Response.json({error:"The current game must be complete before a rematch."},{status:409});if(players.some(p=>!p.faction_id))return Response.json({error:"Every participant must retain a faction."},{status:409});const seats:MultiplayerSeat[]=players.map(p=>({id:p.id,userId:p.user_id??undefined,displayName:p.display_name,controller:p.controller,factionId:p.faction_id!,seatOrder:p.seat_order})),setup:SetupState={stage:"heirs",prepared:prepareMultiplayerAmateur(seats,room.settings),selections:{}};if(!await save(s,room,{status:"active",game_state:setup,review:null,review_acks:[]}))return Response.json({error:"The room changed while the rematch was starting."},{status:409}); }else if(b.action==="choose-faction"){if(room.status!=="waiting"||!MULTIPLAYER_FACTIONS.includes(b.factionId))return Response.json({error:"Choose an available faction before the game begins."},{status:400});if(players.some(p=>p.faction_id===b.factionId&&p.user_id!==user.id))return Response.json({error:"That faction was just taken."},{status:409});const{error}=await s.from("nk_multiplayer_players").update({faction_id:b.factionId}).eq("room_code",room.code).eq("user_id",user.id);if(error)return Response.json({error:"Your faction could not be selected."},{status:409});
 }else if(b.action==="start"){if(room.host_user_id!==user.id||room.status!=="waiting")return Response.json({error:"Only the host can start this waiting game."},{status:403});const expected=room.settings.totalSeats-room.settings.npcCount,humans=players.filter(p=>p.controller==="human");if(humans.length!==expected||humans.some(p=>!p.faction_id))return Response.json({error:"Every human seat and faction choice must be complete."},{status:409});const available=MULTIPLAYER_FACTIONS.filter(f=>!players.some(p=>p.faction_id===f));const assigned=players.map(p=>p.controller==="npc"?{...p,faction_id:available.shift()!}:p);for(const p of assigned.filter(p=>p.controller==="npc"))await s.from("nk_multiplayer_players").update({faction_id:p.faction_id}).eq("id",p.id);const seats:MultiplayerSeat[]=assigned.map(p=>({id:p.id,userId:p.user_id??undefined,displayName:p.display_name,controller:p.controller,factionId:p.faction_id!,seatOrder:p.seat_order}));const setup:SetupState={stage:"heirs",prepared:prepareMultiplayerAmateur(seats,room.settings),selections:{}};if(!await save(s,room,{status:"active",game_state:setup,review:null,review_acks:[]}))return Response.json({error:"The lobby changed. Try again."},{status:409});
 }else if(b.action==="choose-heir"){if(!isSetup(room.game_state))return Response.json({error:"Heir selection is not active."},{status:409});if(!amateurHeirChoices(room.game_state.prepared,user.id).some(c=>c.id===b.heirId))return Response.json({error:"Choose one of your eligible Leaders."},{status:400});const selections={...room.game_state.selections,[user.id]:b.heirId};const humanIds=players.filter(p=>p.controller==="human").map(p=>p.user_id!);const ready=humanIds.every(id=>selections[id]);const game=ready?startMultiplayerAmateur(room.game_state.prepared,selections):{...room.game_state,selections};if(!await save(s,room,{game_state:game}))return Response.json({error:"Another heir choice arrived first. Choose again."},{status:409});
 }else if(b.action==="declare"||b.action==="npc-action"){if(isSetup(room.game_state)||!room.game_state||room.review)return Response.json({error:"The game is waiting for another step."},{status:409});const state=room.game_state as AmateurState;if(state.phase==="replenish"&&b.action==="npc-action"){const pending=state.players.find(p=>p.id===state.pendingReplenishmentPlayerId);if(pending?.controller!=="npc")return Response.json({error:"A human must choose replenishment."},{status:409});resolveNpcReplenishment(state);if(!await save(s,room,{game_state:state}))return Response.json({error:"The game changed."},{status:409});}else{const active=activePlayer(state);let attack:AmateurAttack;if(active.controller==="npc"){if(b.action!=="npc-action")return Response.json({error:"The computer is choosing."},{status:409});attack=chooseNpcAttack(state)}else{if(active.id!==user.id||b.action!=="declare")return Response.json({error:"It is another player's turn."},{status:403});attack={attackerId:b.attackerId,targetPlayerId:b.targetPlayerId,targetId:b.targetId,stat:b.stat};if(!legalAttackers(state).some(c=>c.id===attack.attackerId)||!legalTargets(state,attack.targetPlayerId).some(c=>c.id===attack.targetId)||!["strength","zeal","wealth"].includes(attack.stat))return Response.json({error:"That attack is not legal."},{status:400})}if(!await save(s,room,{review:{kind:"declaration",attack}}))return Response.json({error:"The game changed."},{status:409});}
 }else if(b.action==="resolve"){if(isSetup(room.game_state)||!room.game_state||room.review?.kind!=="declaration")return Response.json({error:"No attack is ready to resolve."},{status:409});const state=room.game_state as AmateurState,active=activePlayer(state);if(active.controller==="human"&&active.id!==user.id)return Response.json({error:"Only the attacker can resolve this attack."},{status:403});const review=resolveMultiplayerAmateur(state,room.review.attack);if(!await save(s,room,{status:state.phase==="complete"?"complete":"active",game_state:state,review,review_acks:[]}))return Response.json({error:"The game changed."},{status:409});
 }else if(b.action==="acknowledge"){if(room.review?.kind!=="result")return Response.json({error:"No result is awaiting confirmation."},{status:409});const state=room.game_state as AmateurState,acks=[...new Set([...(room.review_acks??[]),user.id])],ids=players.filter(p=>p.controller==="human"&&!state.players.find(g=>g.id===p.user_id)?.eliminated).map(p=>p.user_id!);const clear=ids.every(id=>acks.includes(id));if(!await save(s,room,{review:clear?null:room.review,review_acks:clear?[]:acks}))return Response.json({error:"The result changed."},{status:409});
 }else if(b.action==="replenish"){if(isSetup(room.game_state)||!room.game_state||room.review)return Response.json({error:"Replenishment is not ready."},{status:409});const state=room.game_state as AmateurState;if(state.pendingReplenishmentPlayerId!==user.id)return Response.json({error:"Another player has the replenishment choice."},{status:403});if(b.choice==="discard")replenishFromDiscard(state,b.cardId);else if(b.choice==="unused")replenishFromUnused(state);else skipReplenishment(state);if(!await save(s,room,{game_state:state}))return Response.json({error:"The game changed."},{status:409});
 }else return Response.json({error:"Unknown action."},{status:400});const fresh=await load(room.code);return Response.json(payload(fresh.room!,fresh.players,user.id))}
